### ISSUE TITLE
Database Schema Design

### ISSUE THREAD

**Issue by Akgop** [Akgop/SWEngineering-WebApp-Project-2021#2]
기능 명세에 알맞게 필요한 정보를 저장할 수 있는 테이블 스키마 설계 및 검토

**Comment by developerTae** [comment]
DB 설계 검토해보겠습니다.

**Comment by developerTae** [comment]
기능 명세에 맞는 ER 다이어그램을 그려 보겠습니다.

**Comment by developerTae** [comment]
ER 다이어그램을 그리기 전에 테이블 명세서를 작성하면서 구체적인 정의를 다시 하겠습니다.

**Comment by Akgop** [comment]
구체적인 정의, E-R 다이어그램 되면 wiki page 만들어서 올려주세요~

**Comment by developerTae** [comment]
보고서에 작성한 초안으로 테이블 명세서 작성했는데 PK가 없는 테이블도 있고 구체적인 정의도 많이 부족해서 수정이 좀 필요할 것 같아요.
