### ISSUE TITLE
레포지토리 클론해서 server-side 디렉토리 만들고 express + Mysql 환경 구축

### ISSUE THREAD

**Issue by Akgop** [Akgop/SWEngineering-WebApp-Project-2021#9]
레포지토리 클론해서 서버측 코드 모아놓을 수 있도록 server-side/ 만들고 
해당 디렉토리로 이동해서 express-generator로 express 환경 구축하고 서버 켜보고 pr 넣어주세요

그 다음에 Mysql 연동해서 connection 만들고 테이블 만들어서 실험 해보고 pr 넣어주세요

**Comment by developerTae** [comment]
확인했습니다~

**Comment by developerTae** [comment]
server-side에 express 환경 구축해서 서버 켜보고 push 했습니다.

**Comment by developerTae** [comment]
pr 넣었습니다!
